kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pipeline-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3
  volumeMode: Filesystem
