kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: brandonsomoza-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3
  volumeMode: Filesystem
